package com.lojaonline.loja.models;

public enum Situacao {
    PEDIDO_EM_PROCESSAMENTO,
    PEDIDO_CANCELADO,
    AGUARDANDO_PAGAMENTO,
    PAGAMENTO_EM_ANALISE,
    PAGAMENTO_APROVADO,
    PAGAMENTO_RECUSADO,
    EM_TRANSITO_PARA_CLIENTE,
    PEDIDO_ENTREGUE,
    TROCA_SOLICITADA,
    TROCA_EM_ANALISE,
    TROCA_APROVADA,
    TROCA_REJEITADA,
    CUPOM_DE_TROCA_GERADA,
    TROCA_REALIZADA_COM_SUCESSO,
    EM_DEVOLUÇÃO_PARA_O_CLIENTE,
    DEVOLUÇÃO_SOLICITADA,
    DEVOLUÇÃO_EM_ANALISE,
    DEVOLUÇÃO_APROVADA,
    DEVOLUÇÃO_REPROVADA,
    CUPOM_DE_DEVOLUÇÃO_GERADA,
    DEVOLUÇÃO_REALIZADA_COM_SUCESSO;
}
